class TextComponent
{

  HTMLFormElement   textForm;
  HTMLInputElement  textInput;
  HTMLInputElement  textOutput;
  HTMLLabelElement  textOutputLabel;
  HTMLInputElement  checkbox;
  HTMLButtonElement reverseButton;

  TextComponent() 
  {
    // use HTML5 querySelector for DOM retrieval
    textForm         = document.querySelector('#textForm');
    textInput        = textForm.querySelector('#inputText');
    textOutput       = textForm.querySelector('#outputText');
    textOutputLabel  = textForm.querySelector('#outputTextLabel');
    checkbox         = textForm.querySelector('input[type=checkbox]');
    reverseButton    = textForm.querySelector('button[type=submit]');
    
    // listen to checkbox state changes
    checkbox.addEventListener( 'change', handleEvent );
    
    // listen to reverse button clicks
    reverseButton.addEventListener( 'click', handleEvent );
    
    // Listen for input 
    textInput.addEventListener( 'keyup', this.handleEvent );
  }
  
  /**
   * Set the palindrome indicator
   */
  void set isPalindrome ( bool izzit )
  {
    if (izzit) 
      textOutputLabel.innerHTML = "Palindrome Detected";
    else
      textOutputLabel.innerHTML = "Output Text";
  }
  
  /**
   * Set the ouput fields text value
   */
  void set outputText ( String value )
  {
    isPalindrome = false;
    textOutput.value = value;
  }
  
  /**
   * Get the input fields text value
   */
  String get inputText()
  {
    return textInput.value;
  }
    
  /**
   * Handle DOM Events this component is interested in.
   */
  void handleEvent( Event event ) 
  {
    switch( event.type )
    {
      /*
       * A keypress has been detected. If 'Reverse as I type' 
       * is checked, dispatch a text changed event
       */
      case 'keyup':
        if (checkbox.checked) dispatchTextChangedEvent();
        break;
      
      /*
       * The TextComponent's reverse button has been clicked.
       * Prevent the form from submitting, and dispatch a
       * text changed event
       */               
      case 'click':
        event.preventDefault();
        dispatchTextChangedEvent();
        break;
    }
  }

  /**
   * Add EventListeners to TextComponent. TextComponent will
   * dispatch only AppEvent.INPUT_TEXT_CHANGED events, but
   * you can still listen to other events generated by its
   * DOM elements as they propagate through #textForm. 
   * 
   * There is no reason to implement a removeEventListener in
   * this demo, as we never unregister the TextComponentMediator.
   */
  void addEventListener( String type, EventListener listener )
  {
    // delegate to #textForm
    textForm.addEventListener( type, listener );
  }
  
  /**
   * Dispatch an event 
   */
  void dispatchTextChangedEvent()
  {
    Event event = document.createEvent("HTMLEvents");
    event.initEvent(AppEvents.INPUT_TEXT_CHANGED, true, true);
    textForm.dispatchEvent( event );
  }
}